TerapiaOnline/urls.py
from django.contrib import admin
from django.urls import path, include
#estas dos proximas lineas son para servir media files...chequear linea + static ...
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    #Getting the Django pre-built auth urls:
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('therapists.urls', namespace='therapists'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
URL Configuration for the Django project.

The `urlpatterns` list routes URLs to views. For more information, please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/

This configuration includes several URL patterns:

- The admin site is available at '/admin/'.
- The 'main' app's URLs are included at the root path ('/').
- Django's built-in authentication views (login, logout, password change, etc.) are also included at the root path.
- The 'users' app's URLs are included at the root path.
- The 'blog' app's URLs are included at '/blog/'.

Each included URL configuration is associated with a namespace:
- 'main' for the 'main' app.
- 'users' for the 'users' app.
- 'blog' for the 'blog' app.

Namespaces allow you to reverse URLs for included URL configurations. For example, you can use `reverse('blog:post_detail', args=[post_id])` to get the URL for a specific blog post.
"""

blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
app_name = 'blog'

urlpatterns = [
    path('post/new/', PostCreateView.as_view(), name='post-nuevo'),
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detalle'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'), 
    path('post/<str:username>', UserPostListView.as_view(), name='user-posts'), 
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post-detalle', kwargs={"pk": self.pk})
    
    # Metodo para que en la ListView se vea una version reducida del contenido (300 caracteres incluyendo espacios)
    def short_content(self):
        return self.content[:300]
        
    
    
       
    """ 
    In Django, the get_absolute_url method is used to get the canonical URL for an object. It tells Django how to calculate the URL for an object. In your Post model, the get_absolute_url method is using the reverse function to return the URL for the detail view of the post.

    The reverse function in Django is used to generate URLs by reversing the URL patterns defined in your urls.py. It takes a URL pattern name as its first argument and any arguments for the URL pattern as keyword arguments. In your case, reverse('post-detail', kwargs={'pk': self.pk}) is generating a URL for the post-detail view, passing the posts primary key (self.pk) as an argument.

    On the other hand, redirect is a function that returns an HttpResponseRedirect to the appropriate URL for the arguments passed. It can take a model, view name, or URL as its argument, and it will use get_absolute_url if a model is passed.

    So, the main difference between redirect and reverse is that redirect actually sends a redirect response to the user, while reverse simply calculates a URL. You would use reverse when you want to calculate a URL to use elsewhere in your code, and redirect when you want to send the user to a different page in response to an action (like creating a new post). 
    """
    
    

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User


# With class based views, the system renders by default a template with the following convention name:
# <app>/<model>_<viewtype>.html>
# So in this case, the default template name would be:
# blog/post_list.html
class PostListView(ListView):
    model = Post
    ordering = ['-date_posted'] # Orden negativo date_posted. Del ultimo al primer posteo. Como en los mails.
    paginate_by = 5
    
    # IF OLD TEMPLATE AND LOOPING NAMES WOULD HAVE BEEN KEPT:
    # context_object_name = 'manzanas'
    # template_name = 'posts.html'

""" def post_list(request):
    context = {
        'manzanas': Post.objects.all()
    }
    return render(request, 'blog/posts.html', context) """
    
class PostDetailView(DetailView):
    model = Post
    
class PostCreateView(LoginRequiredMixin, CreateView): # El mixin siempre a la izquierda.
    model = Post
    fields = ['title', 'content']
    # Overriding form_valid() method from CreateView, so only logged-in users can post new:
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
 
# UserPassesTestMixin: only the author can update his own post. The test we are creating as a function in the end of the PostUpdateClass.
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    # Test function of the UserPassesTestMixin:
    def test_func(self) -> bool | None:
        post = self.get_object() # Getting the post that we are trying to update. It will return a pk.
        if self.request.user == post.author: # Checking if the current (logged in) user is the author of the post.
            return True
        return False
    
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False
    
class UserPostListView(ListView):
    model = Post
    paginate_by = 5
    template_name = 'blog/user_posts.html'
        
    # Is a method that Django calls to get the list of items to display. In this case, it’s getting a list of Post objects:
    def get_queryset(self):
        # This line is getting the User object that matches the username passed in the URL. If no such user exists, it raises a 404 error:
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')
        
    
    
    
    
    """ 
    The `form_valid` method is a part of Django's class-based views, specifically the `FormView` class, which `CreateView` inherits from²³. 

    In your `PostCreateView` class, you're overriding the `form_valid` method. This method is called when valid form data has been POSTed¹. It's used to define what happens if the form is valid²³.

    In the case of `CreateView`, the parent's `form_valid` method might do some processing (it will call `form.save()` for example)²³. So, when you call `super().form_valid(form)`, you're ensuring that this processing still occurs²³.

    In your specific implementation, you're setting the `author` of the `Post` instance to be the currently logged-in user before calling the parent's `form_valid` method⁴. This means that when a post is created, it's automatically associated with the currently logged-in user.
    
    
    The `PostUpdateView` class you've provided is a Django class-based view that inherits from `LoginRequiredMixin`, `UserPassesTestMixin`, and `UpdateView`. It's used to update an instance of the `Post` model. The class has two methods: `form_valid` and `test_func`.

    1. `form_valid(self, form)`: This method is called when the user submits a valid form. The `form` parameter is the form with data. The method sets the `author` of the `Post` instance to the current logged-in user. It then calls the parent class's `form_valid` method, which saves the form's data to the database.

    2. `test_func(self)`: This method is part of the `UserPassesTestMixin`. It's called to check if the current user passes a certain test condition. In this case, the test is whether the current user is the author of the post. If the user is the author, the method returns `True`; otherwise, it returns `False`. If the test fails (i.e., the method returns `False`), Django will redirect the user to a specified page.
    """


    """  
    user = get_object_or_404(User, username=self.kwargs.get('username')): This line is getting the User object that matches the username passed in the URL. If no such user exists, it raises a 404 error.
    
    So, if you were to navigate to a URL like http://yourwebsite.com/user/johndoe, Django would call the UserPostListView view with username='johndoe'. The get_object_or_404(User, username=self.kwargs.get('username')) line in the view would then attempt to fetch a User object with username='johndoe'. If no such user exists, it would raise a 404 error. If the user does exist, it would return the User object, and the view would proceed to fetch and display all posts authored by that user. 
    """
    
    """ The ordering attribute in Django’s class-based views specifies the default ordering for the entire queryset. However, in this case, the ordering is not uniform for all objects in the queryset. The ordering depends on the specific user, which is determined dynamically based on the username parameter in the URL.

    The get_queryset method allows for more complex queries and dynamic ordering. In this case, it’s used to filter the posts by author and then order them by date_posted. This wouldn’t be possible with a static ordering attribute because the author is not known until the view is called with a specific username. """

blog/templates/blog/article_metadata.html
{% comment %}
TEMPLATE TO BE INCLUDED:
This is the 'article_metadata.html' template. 

It is used to display metadata for a blog article, including the author's name and the date the article was posted. The author's name is linked to a page showing all articles by this author.

The 'object' variable in the context should be an instance of the Article model (or a similar model) with 'author' and 'date_posted' attributes.

This template is designed to be included in other templates using the {% include %} tag, so it can be reused wherever article metadata needs to be displayed.
{% endcomment %}

    <div class="article-metadata">
        <a class="mr-2" href="{% url 'blog:user-posts' object.author.username %}">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
    </div>

blog/templates/blog/post_confirm_delete.html
{% extends "main/base.html" %}
{% block titulo %}New Post{% endblock titulo %}

{% block contenido %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Borrar Post</legend>
                <h3>Esta seguro que quiere borrar el post <span class="text-primary">'{{ object.title }}'</span>?</h3>
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-danger">Si, borrar</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detalle' object.id %}">Cancelar</a>
            </div>
        </form>
    </div>
{% endblock contenido %}

{% comment %} In Django, a DeleteView will render a default template based on the class name. The DeleteView page displayed to a GET request uses a template_name_suffix of '_confirm_delete'. So, if your model is named MyModel, the default template name would be mymodel_confirm_delete.html. If you want to use a different template, you can override this behavior by providing the template_name argument in your view1. For example:

Python
AI-generated code. Review and use carefully. More info on FAQ.

class MyModelDeleteView(DeleteView):
    model = MyModel
    template_name = 'my_template.html'
In this case, my_template.html will be used instead of the default template. {% endcomment %}

blog/templates/blog/post_detail.html
{% extends "main/base.html" %}
{% block contenido %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}" alt="">
        <div class="media-body">
            {% include "blog/article_metadata.html" %}
            <h2 class="article-title">{{ object.title }}</h2>
            <p class="article-content">{{ object.content }}</p>
            {% if object.author == user %} <!--Si el user logeado es el autor del post-->
            <div>
                <a href="{% url 'blog:post-update' object.id %}" class="btn btn-secondary btn-sm mt-1 mb-1">Actualizar</a>
                <a href="{% url 'blog:post-delete' object.id %}" class="btn btn-danger btn-sm mt-1 mb-1">Borrar</a>
            </div>
            {% endif %}
        </div>
    </article>
{% endblock contenido %}

blog/templates/blog/post_form.html
{% extends "main/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %}New Post{% endblock titulo %}

{% block contenido %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
            {{ form|crispy }} 
            </fieldset>
            <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Post</button>
            </div>
        </form>
    </div>
{% endblock contenido %}

blog/templates/blog/post_list.html
{% extends "main/base.html" %}
{% block titulo %}Blog{% endblock titulo %}

{% block contenido %}
    {% for object in object_list %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
            <div class="media-body">
                {% include "blog/article_metadata.html" %}
                {% comment %} Metodo del Post model: (object.get_absolute_url) {% endcomment %}
                <h2><a class="article-title" href="{{ object.get_absolute_url }}">{{ object.title }}</a></h2>
                <p class="article-content">{{ object.short_content }}... <a href="{{ object.get_absolute_url }}">read more</a></p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% include "pagination_controls.html" %}
    {% endif %}



{% endblock contenido %}

blog/templates/blog/user_posts.html
{% extends "main/base.html" %}
{% block titulo %}Blog{% endblock titulo %}

{% block contenido %}
<h2>Publicaciones de: {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h2>
    {% for object in object_list %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
            <div class="media-body">
                {% include "blog/article_metadata.html" %}
                <h2><a class="article-title" href="{% url 'blog:post-detalle' object.id %}">{{ object.title }}</a></h2>
                <p class="article-content">{{ object.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% include "pagination_controls.html" %}
    {% endif %}
{% endblock contenido %}

{% comment %} 
In Django, when a class-based view is used, an instance of the view is actually what’s being called when the URL pattern is matched. This instance includes a number of attributes that can be accessed within the template. One of these attributes is kwargs, which is a dictionary of all keyword arguments passed to the view.

In your URL configuration, you might have a path like this:

path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
Here, <str:username> is a path converter that captures a string argument username from the URL. This captured username is passed as a keyword argument to the UserPostListView.

So, in your template, view.kwargs.username is accessing the username keyword argument that was captured from the URL. This is the username of the user whose posts you’re trying to display.

For example, if you navigate to /user/johndoe, view.kwargs.username in the template would be 'johndoe'. This is used to display the username in the heading of the page: Posts by johndoe. It’s also used to get the count of posts by the user with page_obj.paginator.count. The page_obj is a Page object automatically provided by Django’s pagination system, and paginator is an attribute of Page that represents the Paginator instance. The count attribute of Paginator gives the total number of objects, across all pages. So, page_obj.paginator.count gives the total number of posts by the user. 
{% endcomment %}