TerapiaOnline/urls.py
from django.contrib import admin
from django.urls import path, include
#estas dos proximas lineas son para servir media files...chequear linea + static ...
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    #Getting the Django pre-built auth urls:
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('therapists.urls', namespace='therapists'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
URL Configuration for the Django project.

The `urlpatterns` list routes URLs to views. For more information, please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/

This configuration includes several URL patterns:

- The admin site is available at '/admin/'.
- The 'main' app's URLs are included at the root path ('/').
- Django's built-in authentication views (login, logout, password change, etc.) are also included at the root path.
- The 'users' app's URLs are included at the root path.
- The 'blog' app's URLs are included at '/blog/'.

Each included URL configuration is associated with a namespace:
- 'main' for the 'main' app.
- 'users' for the 'users' app.
- 'blog' for the 'blog' app.

Namespaces allow you to reverse URLs for included URL configurations. For example, you can use `reverse('blog:post_detail', args=[post_id])` to get the URL for a specific blog post.
"""

blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
app_name = 'blog'

urlpatterns = [
    path('post/new/', PostCreateView.as_view(), name='post-nuevo'),
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detalle'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'), 
    path('post/<str:username>', UserPostListView.as_view(), name='user-posts'), 
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='casa'),
    path('home', views.home, name='casa'),
    #Solo se usa para testear base:
    path('base', views.base, name='base'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.registro, name='registro'),
    path('profile/', views.profile, name='perfil'),
    #funcionan sin view explicita, xq usa por default la basica built ins:    
    path('login/', auth_views.LoginView.as_view(), name='login'), 
    path('logout/', auth_views.LogoutView.as_view(), name='logout'), 
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

main/models.py
from django.db import models

class Country(models.Model):
    name = models.CharField(max_length=50)

class City(models.Model):
    name = models.CharField(max_length=50)    

main/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'main/home.html')

#QUEDA PARA TESTEAR base.html CADA TANTO:
def base(request):
    return render(request, 'main/base.html')

""" The `@login_required` decorator in Django is a handy tool that helps secure your views by ensuring that only authenticated users can access them. Here's a simplified explanation of how it works:

1. When you decorate a view function with `@login_required`, Django checks if the user associated with the current request is authenticated³.
2. If the user is authenticated, Django proceeds to execute the view function¹.
3. If the user is not authenticated, Django redirects them to the login page¹.

Here's an example of how you might use it in your code:

from django.contrib.auth.decorators import login_required

@login_required
def my_view(request):
    # Your view logic here
```

In this example, `my_view` is only accessible to users who are logged in. If a user who is not logged in tries to access `my_view`, they will be redirected to the login page.

Behind the scenes, `@login_required` is actually a shortcut for a more general function called `user_passes_test`. This function accepts a test function and applies it to the user. If the user passes the test, they are allowed to access the view. If they fail, they are redirected to the login page¹. The `@login_required` decorator simply uses a test function that checks if `user.is_authenticated` is `True`. """

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='utf-8'>
    <title>{% block titulo %}My Site{% endblock titulo %}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main/main.css' %}">
    <!-- el link a main.css va sin folder xq esta en la misma app que base.html (este archivo) -->

</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr4" href="{% url 'main:casa' %}">Terapia Online</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-link" href="{% url 'main:casa' %}">Home</a>
                        <a class="nav-link" href="{% url 'blog:post-list' %}">Blog</a>
                    </div>
                    <!--Navbar right side-->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <span class="navbar-text usuario">Bienvenido {{user.username}}</span>
                            <a class="nav-link" href="{% url 'blog:post-nuevo' %}">New Post</a>
                            <a class="nav-link" href="{% url 'users:perfil' %}">Perfil</a>
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                            <a class="nav-link" href="{% url 'users:registro' %}">Registrarse</a>
                        {% endif %}
                    </div>
                </div>
            </div>    
        </nav>
    </header>
    <main class="container">
        <div class="row">
            <div class="col-md-8">
                {% if messages %}
                    {% for mensaje in messages %}
                        <div class="alert alert-{{ mensaje.tags }}">
                            {{ mensaje }}
                        </div>
                    {% endfor %}
                {% endif %}
                {% block contenido %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class='text-muted'>You can put any information here you'd like.
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light">Latest Posts</li>
                        <li class="list-group-item list-group-item-light">Announcements</li>
                        <li class="list-group-item list-group-item-light">Calendars</li>
                        <li class="list-group-item list-group-item-light">etc</li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>

</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}
{% block titulo %}Home Page{% endblock titulo %}

{% block contenido %}
<h1>Tal vez la mejor web del universo</h1>
{% endblock contenido %}